language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - build-tools-24.0.1
  - android-24
  licenses:
  - android-sdk-license-.+
script: ./gradlew assemble test
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/